In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dependent=dataset[['charges']]

In [7]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
X_train,X_test,Y_train,Y_test

(      age     bmi  children  sex_male  smoker_yes
 1163   18  28.215         0         0           0
 196    39  32.800         0         0           0
 438    52  46.750         5         0           0
 183    44  26.410         0         0           0
 1298   33  27.455         2         1           0
 ...   ...     ...       ...       ...         ...
 763    27  26.030         0         1           0
 835    42  35.970         2         1           0
 1216   40  25.080         0         1           0
 559    19  35.530         0         1           0
 684    33  18.500         1         0           0

 [936 rows x 5 columns],       age     bmi  children  sex_male  smoker_yes
 578    52  30.200         1         1           0
 610    47  29.370         1         0           0
 569    48  40.565         2         1           1
 1034   61  38.380         0         1           0
 198    51  18.050         0         0           0
 ...   ...     ...       ...       ...         ...
 1261   28  37.100         1         1           0
 494    21  25.700         4         1           1
 97     55  38.280         0         1           0
 418    64  39.160         1         1           0
 920    62  25.000         0         0           0

 [402 rows x 5 columns],           charges
 1163   2200.83085
 196    5649.71500
 438   12592.53450
 183    7419.47790
 1298   5261.46945
 ...           ...
 763    3070.80870
 835    7160.33030
 1216   5415.66120
 559    1646.42970
 684    4766.02200

 [936 rows x 1 columns],           charges
 578    9724.53000
 610    8547.69130
 569   45702.02235
 1034  12950.07120
 198    9644.25250
 ...           ...
 1261   3277.16100
 494   17942.10600
 97    10226.28420
 418   14418.28040
 920   13451.12200

 [402 rows x 1 columns])

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split




param_grid = {'n_estimators':[50,100,200,500],'learning_rate':[0.01,0.1,0.2,0.5],'loss':['linear','square','exponential'] }
grid = GridSearchCV(AdaBoostRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, Y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 48 candidates, totalling 144 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    9.5s
[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:   23.2s
[Parallel(n_jobs=-1)]: Done 144 out of 144 | elapsed:   28.6s finished
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=AdaBoostRegressor(base_estimator=None, learning_rate=1.0,
                                         loss='linear', n_estimators=50,
                                         random_state=None),
             iid='warn', n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2, 0.5],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 200, 500]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [15]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'learning_rate': 0.01, 'loss': 'linear', 'n_estimators': 50}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_loss,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.205541,0.015618,0.019655,3.088617e-03,0.01,linear,50,"{'learning_rate': 0.01, 'loss': 'linear', 'n_e...",0.840047,0.837697,0.821970,0.833238,0.008025,1
1,0.352449,0.004918,0.029982,3.371748e-07,0.01,linear,100,"{'learning_rate': 0.01, 'loss': 'linear', 'n_e...",0.833222,0.837238,0.823511,0.831324,0.005763,5
2,0.677251,0.010268,0.053300,1.245706e-03,0.01,linear,200,"{'learning_rate': 0.01, 'loss': 'linear', 'n_e...",0.822443,0.832841,0.821145,0.825476,0.005235,8
3,1.694291,0.083637,0.157571,3.435169e-02,0.01,linear,500,"{'learning_rate': 0.01, 'loss': 'linear', 'n_e...",0.797644,0.818617,0.814920,0.810393,0.009141,12
4,0.167230,0.002356,0.015657,4.709778e-04,0.01,square,50,"{'learning_rate': 0.01, 'loss': 'square', 'n_e...",0.837847,0.837372,0.822392,0.832537,0.007176,2
5,0.356781,0.012020,0.042641,1.326640e-02,0.01,square,100,"{'learning_rate': 0.01, 'loss': 'square', 'n_e...",0.829596,0.835080,0.823972,0.829550,0.004535,6
6,0.803504,0.025438,0.054965,1.413156e-03,0.01,square,200,"{'learning_rate': 0.01, 'loss': 'square', 'n_e...",0.803982,0.824556,0.818599,0.815712,0.008644,9
7,1.724272,0.035776,0.127255,2.492792e-03,0.01,square,500,"{'learning_rate': 0.01, 'loss': 'square', 'n_e...",0.727803,0.777765,0.799741,0.768436,0.030100,27
8,0.176558,0.003769,0.016323,4.711456e-04,0.01,exponential,50,"{'learning_rate': 0.01, 'loss': 'exponential',...",0.837906,0.837781,0.821810,0.832499,0.007559,3
9,0.350783,0.009268,0.027650,4.706401e-04,0.01,exponential,100,"{'learning_rate': 0.01, 'loss': 'exponential',...",0.834958,0.837471,0.823118,0.831849,0.006258,4
10,0.679249,0.006646,0.056299,4.986327e-03,0.01,exponential,200,"{'learning_rate': 0.01, 'loss': 'exponential',...",0.828362,0.835164,0.823350,0.828959,0.004841,7
11,1.710614,0.010492,0.135250,1.086605e-02,0.01,exponential,500,"{'learning_rate': 0.01, 'loss': 'exponential',...",0.800204,0.819724,0.815423,0.811784,0.008374,11
12,0.170228,0.006179,0.016323,4.709208e-04,0.1,linear,50,"{'learning_rate': 0.1, 'loss': 'linear', 'n_es...",0.795841,0.823267,0.811532,0.810214,0.011235,13
13,0.230525,0.039323,0.020321,2.493259e-03,0.1,linear,100,"{'learning_rate': 0.1, 'loss': 'linear', 'n_es...",0.795808,0.809947,0.809209,0.804988,0.006498,17
14,0.218199,0.031660,0.020987,2.158656e-03,0.1,linear,200,"{'learning_rate': 0.1, 'loss': 'linear', 'n_es...",0.790370,0.816205,0.816015,0.807530,0.012134,15
15,0.237854,0.037775,0.020655,2.865783e-03,0.1,linear,500,"{'learning_rate': 0.1, 'loss': 'linear', 'n_es...",0.795916,0.804268,0.809144,0.803110,0.005462,18
16,0.184220,0.013267,0.015991,7.018853e-07,0.1,square,50,"{'learning_rate': 0.1, 'loss': 'square', 'n_es...",0.721588,0.774318,0.792780,0.762895,0.030166,28
17,0.336794,0.001632,0.028316,1.246980e-03,0.1,square,100,"{'learning_rate': 0.1, 'loss': 'square', 'n_es...",0.617566,0.698075,0.747717,0.687786,0.053630,31
18,0.651932,0.004986,0.056632,5.903998e-03,0.1,square,200,"{'learning_rate': 0.1, 'loss': 'square', 'n_es...",0.504591,0.598726,0.676343,0.593220,0.070225,35
19,1.606012,0.007113,0.133918,7.478758e-03,0.1,square,500,"{'learning_rate': 0.1, 'loss': 'square', 'n_es...",0.409172,0.512412,0.564321,0.495302,0.064484,44
20,0.169229,0.002054,0.016323,4.708084e-04,0.1,exponential,50,"{'learning_rate': 0.1, 'loss': 'exponential', ...",0.805469,0.820693,0.820938,0.815700,0.007235,10
21,0.337793,0.001632,0.027650,4.713704e-04,0.1,exponential,100,"{'learning_rate': 0.1, 'loss': 'exponential', ...",0.746656,0.786263,0.797116,0.776678,0.021686,26
22,0.684913,0.009386,0.053965,1.412257e-03,0.1,exponential,200,"{'learning_rate': 0.1, 'loss': 'exponential', ...",0.653415,0.717613,0.746442,0.705824,0.038882,29
23,1.682299,0.014375,0.143247,1.113873e-02,0.1,exponential,500,"{'learning_rate': 0.1, 'loss': 'exponential', ...",0.525683,0.576349,0.663106,0.588380,0.056744,37
24,0.111931,0.013358,0.011992,1.413830e-03,0.2,linear,50,"{'learning_rate': 0.2, 'loss': 'linear', 'n_es...",0.796405,0.811233,0.815834,0.807824,0.008290,14
25,0.125590,0.025301,0.012992,1.632193e-03,0.2,linear,100,"{'learning_rate': 0.2, 'loss': 'linear', 'n_es...",0.794264,0.799083,0.809100,0.800816,0.006180,20
26,0.115929,0.026264,0.012327,1.244199e-03,0.2,linear,200,"{'learning_rate': 0.2, 'loss': 'linear', 'n_es...",0.777113,0.798190,0.811794,0.795699,0.014268,22
27,0.159568,0.007841,0.015991,2.943464e-03,0.2,linear,500,"{'learning_rate': 0.2, 'loss': 'linear', 'n_es...",0.760372,0.798685,0.809654,0.789570,0.021126,24
28,0.184887,0.001632,0.015990,4.495664e-07,0.2,square,50,"{'learning_rate': 0.2, 'loss': 'square', 'n_es...",0.623685,0.698180,0.738862,0.686909,0.047691,32
29,0.344788,0.009196,0.029316,1.247256e-03,0.2,square,100,"{'learning_rate': 0.2, 'loss': 'square', 'n_es...",0.503715,0.592707,0.652790,0.583071,0.061240,38
30,0.637275,0.008214,0.052634,4.712019e-04,0.2,square,200,"{'learning_rate': 0.2, 'loss': 'square', 'n_es...",0.432537,0.528278,0.562789,0.507868,0.055099,42
31,1.603346,0.018614,0.134584,2.493174e-03,0.2,square,500,"{'learning_rate': 0.2, 'loss': 'square', 'n_es...",0.366950,0.490331,0.514872,0.457385,0.064727,47
32,0.168564,0.001247,0.016324,4.715390e-04,0.2,exponential,50,"{'learning_rate': 0.2, 'loss': 'exponential', ...",0.748367,0.787765,0.794538,0.776890,0.020358,25
33,0.342122,0.006231,0.030315,1.246364e-03,0.2,exponential,100,"{'learning_rate': 0.2, 'loss': 'exponential', ...",0.643925,0.719117,0.741011,0.701351,0.041579,30
34,0.699903,0.011139,0.054968,1.730247e-06,0.2,exponential,200,"{'learning_rate': 0.2, 'loss': 'exponential', ...",0.544247,0.607866,0.689739,0.613950,0.059552,34
35,1.757917,0.031928,0.145244,1.125736e-02,0.2,exponential,500,"{'learning_rate': 0.2, 'loss': 'exponential', ...",0.454764,0.507375,0.608169,0.523436,0.063649,40
36,0.064960,0.014344,0.008662,9.427408e-04,0.5,linear,50,"{'learning_rate': 0.5, 'loss': 'linear', 'n_es...",0.784962,0.797284,0.803806,0.795351,0.007814,23
37,0.062961,0.003264,0.008996,8.161456e-04,0.5,linear,100,"{'learning_rate': 0.5, 'loss': 'linear', 'n_es...",0.793993,0.804757,0.805226,0.801325,0.005188,19
38,0.055966,0.004318,0.009327,1.246831e-03,0.5,linear,200,"{'learning_rate': 0.5, 'loss': 'linear', 'n_es...",0.778179,0.817641,0.795647,0.797156,0.016146,21
39,0.053634,0.012277,0.007995,8.153667e-04,0.5,linear,500,"{'learning_rate': 0.5, 'loss': 'linear', 'n_es...",0.805131,0.806842,0.808656,0.806876,0.001439,16
40,0.172227,0.001885,0.018988,1.632193e-03,0.5,square,50,"{'learning_rate': 0.5, 'loss': 'square', 'n_es...",0.488634,0.566761,0.656843,0.570746,0.068729,39
41,0.373104,0.013466,0.029982,2.159171e-03,0.5,square,100,"{'learning_rate': 0.5, 'loss': 'square', 'n_es...",0.423922,0.508391,0.563110,0.498475,0.057254,43
42,0.671254,0.008951,0.059298,4.493947e-03,0.5,square,200,"{'learning_rate': 0.5, 'loss': 'square', 'n_es...",0.376954,0.490541,0.530425,0.465974,0.065018,46
43,1.595352,0.253217,0.120259,1.743070e-02,0.5,square,500,"{'learning_rate': 0.5, 'loss': 'square', 'n_es...",0.347340,0.477161,0.491315,0.438605,0.064793,48
44,0.177891,0.006679,0.017656,1.246640e-03,0.5,exponential,50,"{'learning_rate': 0.5, 'loss': 'exponential', ...",0.624638,0.677738,0.722981,0.675119,0.040191,33
45,0.360447,0.031547,0.029647,2.353030e-03,0.5,exponential,100,"{'learning_rate': 0.5, 'loss': 'exponential', ...",0.522933,0.576842,0.665378,0.588384,0.058723,36
46,0.717224,0.053092,0.053634,9.426283e-04,0.5,exponential,200,"{'learning_rate': 0.5, 'loss': 'exponential', ...",0.439125,0.508710,0.604146,0.517327,0.067645,41
47,1.613008,0.004079,0.126921,2.827829e-03,0.5,exponential,500,"{'learning_rate': 0.5, 'loss': 'exponential', ...",0.396932,0.487858,0.548081,0.477624,0.062129,45

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:43
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[45637.52095164]